### ISSUE TITLE
Use a distroless base image

### ISSUE THREAD

**Issue by sellitforcache** [TremoloSecurity/kube-oidc-proxy#40]
Is there a particular reason to use Ubuntu?  From a quick skim, it doesn't seem like there are shared lib or os dependencies, so why build the binary into a big image?  You mentioned something about DNS on the website...

**Comment by mlbiam** [comment]
When we originally forked kube-oidc-proxy it was based on Alpine, which used musl with a severely limited DNS implementation.  So between this, and:

1. Alpine has no commercial support
2. Most of our customers are enterprises that have support contracts for Ubuntu
3. I didn't want to use scratch or a distroless base because the proxy is ultimately an integration tool and if there's an issue I knew the first thing users would do is exec in and try to use ping, nslookup, curl, etc. `kubectl debug` was still pretty new (if it was even released yet) so I wasn't ready to rely on it for debugging.
4. OpenUnison and the OpenUnison operator both run on Ubuntu so I wanted to keep things consistent across our stack
5. We already had the infrastructure in place to watch for patched CVEs and rebuild as needed

At the time, I didn't see the benefit.  Now that Wolfi exists, while built on Alpine it uses glibc instead of musl, and `kubectl debug` is much easier to use, I've thought about moving to that but its been lower on the priority stack.
